### ISSUE TITLE
Soft relaunch Website: Design 2.0

### ISSUE THREAD

**Issue by GregOnNet** [co-IT/co-it.github.io#19]
This issue summarizes all tasks we will solve due to apply the new design for our website.

## ToDo

- [ ] co-IT/co-it.github.io#23
                  
## Done

- [x] co-IT/co-it.github.io#22
- [x] co-IT/co-it.github.io#21
- [x] co-IT/co-it.github.io#25
- [x] #31 
- [x] https://github.com/co-IT/co-it.github.io/issues/26
- [x] co-IT/co-it.github.io#8
- [x] co-IT/co-it.github.io#24
- [x] https://github.com/co-IT/co-it.github.io/issues/30
- [x] co-IT/co-it.github.io#20
- [x] co-IT/co-it.github.io#10
- [x] co-IT/co-it.github.io#10
- [x] co-IT/co-it.github.io#11
- [x] co-IT/change-pioneers#130
- [x] co-IT/change-pioneers#132
- [x] co-IT/co-it.github.io#2
- [x] co-IT/co-it.github.io#7
- [x] co-IT/co-it.github.io#1
- [x] co-IT/co-it.github.io#5
- [x] co-IT/co-it.github.io#6
- [x] Add 3rd Header-Category for contact, impressum, datenschutz, AGB
- [x] Recruitee Job Tiles
